changedFieldIndicator: 2123454810
field: 65d97c16-0fb7-4ce6-a756-11b066009e73 # Card
fieldLayouts:
  f42cc502-58d1-4ef8-8992-26afbd8e7156:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d68fe90d-f28e-47be-8a8d-5c94b9b4830b # Card Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 860f66b2-215c-4ccd-9fa2-70c330ef5fc7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3dfeadf-4aff-469c-a53f-3a9bfec5b991 # Card Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9be14e23-1df4-4715-bbe8-8d8a0a09d17b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eafd68f7-80d2-4d9c-9221-8524cc96cb5f # Card Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b9aa651-4bed-4707-a98a-03b913b619df
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 61a05b5e-dd68-4281-88fd-73c8b680d372
        userCondition: null
fields:
  b3dfeadf-4aff-469c-a53f-3a9bfec5b991: # Card Text
    columnSuffix: tevxbdmo
    contentColumnType: text
    fieldGroup: null
    handle: cardText
    instructions: null
    name: 'Card Text'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  d68fe90d-f28e-47be-8a8d-5c94b9b4830b: # Card Title
    columnSuffix: rjboddqc
    contentColumnType: text
    fieldGroup: null
    handle: cardTitle
    instructions: null
    name: 'Card Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  eafd68f7-80d2-4d9c-9221-8524cc96cb5f: # Card Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardLink
    instructions: null
    name: 'Card Link'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: asset
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
